import type BuildMetadata from "@/types/buildMetadata";
// This file is auto-generated by the build system.
const meta: BuildMetadata = {
  version: "0.0.0",
  date: "2023-01-05T14:31:44.319Z",
};
export default meta;
