import type BuildMetadata from "@/types/buildMetadata";
// This file is auto-generated by the build system.
const meta: BuildMetadata = {
  version: "0.0.0",
  date: "2023-01-06T16:16:15.077Z",
};
export default meta;
