import type MetaInterface from '@/interfaces/MetaInterface';
      // This file is auto-generated by the build system.
      const meta: MetaInterface = {
        version: '0.0.0',
        date: '2023-01-04T17:50:35.690Z',
      };
      export default meta;
    